apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockwork
spec:
  replicas: 1
  selector:
    matchLabels:
      de-app: clockwork
  template:
    metadata:
      labels:
        de-app: clockwork
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - clockwork
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: clockwork.properties
                path: clockwork.properties
      containers:
        - name: clockwork
          image: harbor.cyverse.org/de/clockwork
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
          args:
            - --config
            - /etc/iplant/de/clockwork.properties
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
      restartPolicy: Always
